[project]
name = "scout"
version = "0.1.0"
description = "API for Scout"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.124.0",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
